name: Fixed 24-7 Automation
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Packages
        run: python -m pip install requests

      - name: Run Python Code
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          import os
          import requests
          print("If you see this, it finally worked!")
